run:
  tests: true
  build-tags:
    - bench

linters-settings:
  depguard:
    rules:
      main:  # ← Changed from "Main" to "main"
        files:
          - ^internal/.*
          - ^cmd/.*
        allowRegexp: true
        allow:
          - $gostd
          - ^google\.golang\.org/grpc(/.*)?$
          - ^google\.golang\.org/protobuf(/.*)?$  # ← Broader pattern
          - ^github\.com/grpc-ecosystem/grpc-gateway(/.*)?$  # ← Broader pattern
          - ^github\.com/whatafunc/Golang_Otus_Labs/hw12_13_14_15_16_calendar(/.*)?$  # ← Broader pattern

      test:  # ← Changed from "Test" to "test"
        files:
          - _test\.go$
        allowRegexp: true
        allow:
          - $gostd  # ← CRITICAL: Added this line
          - ^github\.com/stretchr/testify(/.*)?$
          - ^github\.com/whatafunc/Golang_Otus_Labs/hw12_13_14_15_16_calendar(/.*)?$  # ← Broader pattern

      NoCmdImports:
        files:
          - ^(?!cmd/).*\.go$
        allowRegexp: true
        allow:
          - $gostd
        denyRegexp:
          - ^github\.com/whatafunc/Golang_Otus_Labs/hw12_13_14_15_16_calendar/cmd(/.*)?$
        message: "Do not import cmd/ from non-cmd packages (clean architecture rule)"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace